resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub
    trigger:
    - '*'

extends:
  template: pipeline/nuget.yml@templates
  parameters:
    parameter.projectName: 'dotnet.cleanarchitect.Core'
