resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub

extends:
  template: pipelines/nuget.yml@templates
  parameters:
    projectName: ${{ variables['Build.DefinitionName'] }}
