#resources:
#  repositories:
#  - repository: templates
#    type: git
#    name: MyProject/MyTemplates
#    ref: refs/tags/v1

extends:
  #template: template.yml@templates
  template: nuget.build.yml
  parameters:
    parameter.projectName: 'dotnet.cleanarchitect.Core'
